package app;

import dao.MedicineDAO;
import model.Medicine;

public class Main {

    public static void main(String[] args) {

        MedicineDAO medicineDAO = new MedicineDAO();

        Medicine medicine = new Medicine(
                0,                      // Auto-generated by MySQL
                "Vitamin C 500",
                "Ascorbic Acid",
                "Tablet",
                "VIT501",
                "2025-07-20",
                "2027-07-20",
                30.00,
                45.00,
                100,
                "D5",
                2
        );

        boolean inserted = medicineDAO.addMedicine(medicine);

        if (inserted) {
            System.out.println("Medicine Added Successfully!");
        } else {
            System.out.println("Failed to Add Medicine!");
        }
    }
}